<title>Forum</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="./style.css"/>
<script type="text/JavaScript" src="ajax/ajax.js"></script>
<script type="text/JavaScript" src="jquery/jquery-1.7.2.min.js"></script>
<link rel="stylesheet" type="text/css" href="jquery/css/jquery.lightbox-0.5.css" media="screen" />
<script type="text/javascript" src="jquery/jquery.lightbox-0.5.js"></script>